require 'rake/clean'

PRG = 'gif-reader'

CLOBBER.include("out/#{PRG}.js")
CLEAN.include('doc/top-summary.md')

tool_doc_top = "../../tools/doc-top"

task :default => "out/#{PRG}.js"

@coffeeImg = [
	'photo',
	'pointer',
	'logo'
]

@deps = [
	'../../lib/base64.js',
	'../../lib/gif-reader.js',
	'doc/top-summary.md',
	'src/app.js',
	"#{PRG}.m4"
]


@coffeeImg.each do |id|
	@deps.push "gen/#{id}.js"
	file "gen/#{id}.coffee" => [ "img/#{id}.gif" ] do
		sh "echo '#{id}Data = \"' > gen/#{id}.coffee"
		sh "recode data..b64 < img/#{id}.gif >> gen/#{id}.coffee"
		sh "echo '\"' >> gen/#{id}.coffee"
	end

	file "gen/#{id}.js" => [ "gen/#{id}.coffee" ] do
		sh "coffee -b -o gen/ gen/#{id}.coffee"
	end
end

file 'doc/top-summary.md' => [ 'info.yml' ] do
	sh tool_doc_top
end

file "out/#{PRG}.js" => @deps do
	sh "m4 -I ../../lib -P #{PRG}.m4 > out/#{PRG}.js"
end
