PRG = 'portia-puzzles'

@deps = [
	'../../lib/util-class.js',
	'../../lib/util-global.js',
	'../../lib/lib-jqueryui.js',
	'../../lib/lib-mam.js',
	'src/graphics.js',
	'src/app.js',
	'src/states-warmup.js',
	'src/states-menus.js',
	'src/states-stories.js',
	'src/states-rooms.js',
	'src/states-extras.js'
]

@less = [ 'portia' ]
@html = [ 'ui' ]

import "#{File.dirname(__FILE__)}/../../tools/rake-common.rb"
