require 'rake/clean'

CLOBBER.include('src/svglite-demo.js')

task :default => 'src/svglite-demo.js'

@deps = [
	'../lib/util-class.js',
	'../lib/canvas-wrapper.js',
	'../lib/parser-base.js',
	'../lib/svg-lite.js',
	'src/main.js',
	'svglite-demo.m4'
]

file 'src/svglite-demo.js' => @deps do
	sh "m4 -I ../lib -I ./src -P svglite-demo.m4 > src/svglite-demo.js"
end
