require 'rake/clean'

PRG = 'image2code'

CLOBBER.include("out/#{PRG}.js")
CLEAN.include('gen/top-summary.md')

tool_doc_top = "../../tools/doc-top"

task :default => "out/#{PRG}.js"

@coffeeGen = [
	'html-ui',
	'imgcode-template'
]

@deps = [
	'../../lib/global-iface.js',
	'gen/top-summary.md',
	'src/background.js',
	'src/app.js',
	"#{PRG}.m4"
]


@coffeeGen.each do |coffee|
	@deps.push "gen/#{coffee}.js"
	file "gen/#{coffee}.js" => [ "src/#{coffee}.coffee" ] do
		sh "coffee -b -o gen/ src/#{coffee}.coffee"
	end
end

file 'gen/top-summary.md' => [ 'info.yml' ] do
	sh tool_doc_top
end

file "out/#{PRG}.js" => @deps do
	sh "m4 -I ../../lib -P #{PRG}.m4 > out/#{PRG}.js"
end
