require 'rake/clean'

PRG = 'chemical-formulas'

CLOBBER.include("out/#{PRG}.js")
CLEAN.include('doc/top-summary.md')

tool_doc_top = "../../tools/doc-top"

task :default => "out/#{PRG}.js"

@deps = [
	'../../lib/util-class.js',
	'../../lib/parser-base.js',
	'../../lib/global-iface.js',
	'doc/top-summary.md',
	'gen/elements.js',
	'gen/html-ui.js',
	'src/formula.js',
	'src/chem-parser.js',
	'src/app.js',
	"#{PRG}.m4"
]

file 'doc/top-summary.md' => [ 'info.yml' ] do
	sh tool_doc_top
end

file 'gen/html-ui.js' => [ 'src/html-ui.coffee' ] do
	sh "coffee -b -o gen/ src/html-ui.coffee"
end

file "out/#{PRG}.js" => @deps do
	sh "m4 -I ../../lib -I src/ -P #{PRG}.m4 > out/#{PRG}.js"
end
