pointerData = """
R0lGODlhHgAnAIABAAAAAP///yH5BAEKAAEALAAAAAAeACcAAAJ1jI+py+1/gITUSFDftDivHYAe
AoojF3Vnyq5tqLrlFXvzJau36cxv5rOQeIpgiIRqGGMdES0JiyClQg6xOD1aawwm9VfRJbgUJtmG
dWmzK+45/Hlr4jL66LoGyvH2rry49zcmKBhVVlaYp5RI0+jI+BipVlEAADs=
"""
