// Generated by CoffeeScript 1.3.3
var pointerData;

pointerData = "R0lGODlhHgAnAIABAAAAAP///yH5BAEKAAEALAAAAAAeACcAAAJ1jI+py+1/gITUSFDftDivHYAe\nAoojF3Vnyq5tqLrlFXvzJau36cxv5rOQeIpgiIRqGGMdES0JiyClQg6xOD1aawwm9VfRJbgUJtmG\ndWmzK+45/Hlr4jL66LoGyvH2rry49zcmKBhVVlaYp5RI0+jI+BipVlEAADs=";
