require 'rake/clean'

CLOBBER.include('cloth.js')

task :default => 'cloth.js'

@deps = [
	'../lib/particles.js',
	'../lib/text-layer.js',
	'../lib/gui.js',
	'cloth-main.js',
	'cloth.m4'
]

file 'cloth.js' => @deps do
	sh "m4 -I ../lib -P cloth.m4 > cloth.js"
end
