PRG = 'cloth-simulation'

@deps = [
	'../../lib/util-class.js',
	'../../lib/particles.js',
	'../../lib/canvas-wrapper.js',
	'../../lib/gui.js',
	'src/app.js'
]

import "#{File.dirname(__FILE__)}/../../tools/rake-common.rb"
