require 'rake/clean'

CLOBBER.include('out/snowman-ii.js')
CLEAN.include('doc/top-summary.md')

tool_doc_top = "../tools/doc-top"

task :default => 'out/snowman-ii.js'

@deps = [
	'../lib/util-colors.js',
	'../lib/heap.js',
	'../lib/timer.js',
	'../lib/particles.js',
	'../lib/canvas-wrapper.js',
	'../lib/keys-indicator.js',
	'doc/top-summary.md',
	'src/snow.js',
	'src/snowman.js',
	'src/main.js',
	'snowman-ii.m4'
]

file 'doc/top-summary.md' => [ 'info.yml' ] do
        sh tool_doc_top
end

file 'out/snowman-ii.js' => @deps do
	sh "m4 -I ../lib -I src/ -P snowman-ii.m4 > out/snowman-ii.js"
end
