require 'rake/clean'

CLOBBER.include('snowman-ii.js')

task :default => 'snowman-ii.js'

@deps = [
	'../lib/dollar-basic.js',
	'../lib/heap.js',
	'../lib/dollar-timers.js',
	'../lib/particles.js',
	'../lib/keys-indicator.js',
	'snow.js',
	'snowman.js',
	'snowman-ii-main.js',
	'snowman-ii.m4'
]

file 'snowman-ii.js' => @deps do
	sh "m4 -I ../lib -P snowman-ii.m4 > snowman-ii.js"
end
